#include "stdint.h"

typedef enum {_pbsClearSector, _pbsFillSector} TProgressBarSector;

typedef enum {_taLeft, _taCenter, _taRight} TTextAlign;
typedef enum {_tavTop, _tavMiddle, _tavBottom} TTextAlignVertical;

typedef struct Screen TScreen;

typedef struct {
  unsigned int X_Min;
  unsigned int X_Max;
  unsigned int Y_Min;
  unsigned int Y_Max;
  char         Rotate;
} TTPConstants;

typedef struct  Button {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign    TextAlign;
  TTextAlignVertical TextAlignVertical;
  const char    *FontName;
  unsigned int  Font_Color;
  char          VerticalText;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TButton;

typedef struct  Button_Round {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          *Caption;
  TTextAlign    TextAlign;
  TTextAlignVertical TextAlignVertical;
  const char    *FontName;
  unsigned int  Font_Color;
  char          VerticalText;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          Corner_Radius;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TButton_Round;

typedef struct  Label {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          *Caption;
  const char    *FontName;
  unsigned int  Font_Color;
  char          VerticalText;
  char          Visible;
  char          Active;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TLabel;

typedef struct  Image {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  const char    *Picture_Name;
  char          Visible;
  char          Active;
  char          Picture_Type;
  char          Picture_Ratio;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TImage;

typedef struct  Circle {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Radius;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Active;
  char          Transparent;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  char          PressColEnabled;
  unsigned int  Press_Color;
  void          (*OnUpPtr)();
  void          (*OnDownPtr)();
  void          (*OnClickPtr)();
  void          (*OnPressPtr)();
} TCircle;

typedef struct ProgressBar {
  TScreen*  OwnerScreen;
  char          Order;
  unsigned int  Left;
  unsigned int  Top;
  unsigned int  Width;
  unsigned int  Height;
  char          Pen_Width;
  unsigned int  Pen_Color;
  char          Visible;
  char          Transparent;
  char          *Caption;
  const char    *FontName;
  unsigned int  Font_Color;
  char          Gradient;
  char          Gradient_Orientation;
  unsigned int  Gradient_Start_Color;
  unsigned int  Gradient_End_Color;
  unsigned int  Color;
  unsigned int  Background_Color;
  unsigned int  Min;
  unsigned int  Max;
  unsigned int  Position;
  unsigned int  Prev_Position;
  char          Show_Position;
  char          Show_Percentage;
  char          Smooth;
  char          Rounded;
  char          Corner_Radius;
} TProgressBar;

struct Screen {
  unsigned int           Color;
  unsigned int           Width;
  unsigned int           Height;
  unsigned int           ObjectsCount;
  unsigned int           ButtonsCount;
  TButton                * const code *Buttons;
  unsigned int           Buttons_RoundCount;
  TButton_Round          * const code *Buttons_Round;
  unsigned int           LabelsCount;
  TLabel                 * const code *Labels;
  unsigned int           ImagesCount;
  TImage                 * const code *Images;
  unsigned int           CirclesCount;
  TCircle                * const code *Circles;
  unsigned int           ProgressBarsCount;
  TProgressBar           * const code *ProgressBars;
};

extern   TScreen                Screen1;
extern   TImage               Image2;
extern   TImage               Image4;
extern   TLabel                 temperature_label;
extern   TLabel                 Label1;
extern   TLabel                 Label2;
extern   TLabel                 humidity_label;
extern   TLabel                 Label3;
extern   TLabel                 uv_label;
extern   TLabel                 Label4;
extern   TLabel                 Label5;
extern   TLabel                 Label6;
extern   TLabel                 Label10;
extern   TCircle                Circle1;
extern   TButton_Round          ButtonRound1;
extern   TImage               Image6;
extern   TImage               Image7;
extern   TImage               Image8;
extern   TImage               Image9;
extern   TButton_Round          * const code Screen1_Buttons_Round[1];
extern   TLabel                 * const code Screen1_Labels[10];
extern   TImage                 * const code Screen1_Images[6];
extern   TCircle                * const code Screen1_Circles[1];

extern   TScreen                Screen2;
extern   TImage               Image10;
extern   TImage               Image3;
extern   TProgressBar                 ProgressBar1;
extern   TButton               servo_position_button_2;
extern   TButton               servo_position_button_1;
extern   TImage               Image5;
extern   TButton               servo_number_button_1;
extern   TButton               servo_number_button_2;
extern   TButton               servo_number_button_4;
extern   TButton               servo_number_button_6;
extern   TButton               servo_number_button_5;
extern   TButton               servo_number_button_7;
extern   TButton               servo_number_button_8;
extern   TButton               servo_number_button_9;
extern   TButton               servo_number_button_10;
extern   TButton               servo_number_button_11;
extern   TButton               servo_number_button_12;
extern   TButton               servo_number_button_13;
extern   TButton               servo_number_button_14;
extern   TButton               servo_number_button_15;
extern   TButton               servo_number_button_16;
extern   TButton               servo_number_button_3;
extern   TButton               servo_number_button_all;
extern   TButton               servo_position_button_3;
extern   TButton               servo_position_button_4;
extern   TButton               servo_position_button_5;
extern   TButton               servo_position_button_6;
extern   TButton               servo_position_button_7;
extern   TButton               servo_position_button_8;
extern   TButton               servo_position_button_9;
extern   TButton               fan_speed_button_1;
extern   TButton               fan_speed_button_3;
extern   TButton               fan_speed_button_5;
extern   TButton               fan_speed_button_stop;
extern   TLabel                 Label7;
extern   TLabel                 Label8;
extern   TLabel                 Label9;
extern   TButton               fan_speed_button_7;
extern   TButton_Round          ButtonRound2;
extern   TButton               fan_speed_button_2;
extern   TButton               fan_speed_button_4;
extern   TButton               fan_speed_button_6;
extern   TButton                * const code Screen2_Buttons[34];
extern   TButton_Round          * const code Screen2_Buttons_Round[1];
extern   TLabel                 * const code Screen2_Labels[3];
extern   TImage                 * const code Screen2_Images[3];
extern   TProgressBar           * const code Screen2_ProgressBars[1];

extern   TScreen                Screen3;
extern   TImage               Image1;
extern   TImage                 * const code Screen3_Images[1];


/////////////////////////
// Events Code Declarations
void ButtonRound1OnClick();
void ButtonRound2OnClick();
void fan_speed_button_1OnClick();
void fan_speed_button_2OnClick();
void fan_speed_button_3OnClick();
void fan_speed_button_4OnClick();
void fan_speed_button_5OnClick();
void fan_speed_button_6OnClick();
void fan_speed_button_7OnClick();
void fan_speed_button_stopOnClick();
void servo_number_button_10OnClick();
void servo_number_button_11OnClick();
void servo_number_button_12OnClick();
void servo_number_button_13OnClick();
void servo_number_button_14OnClick();
void servo_number_button_15OnClick();
void servo_number_button_16OnClick();
void servo_number_button_1OnClick();
void servo_number_button_2OnClick();
void servo_number_button_3OnClick();
void servo_number_button_4OnClick();
void servo_number_button_5OnClick();
void servo_number_button_6OnClick();
void servo_number_button_7OnClick();
void servo_number_button_8OnClick();
void servo_number_button_9OnClick();
void servo_number_button_allOnClick();
void servo_position_button_1OnClick();
void servo_position_button_2OnClick();
void servo_position_button_3OnClick();
void servo_position_button_4OnClick();
void servo_position_button_5OnClick();
void servo_position_button_6OnClick();
void servo_position_button_7OnClick();
void servo_position_button_8OnClick();
void servo_position_button_9OnClick();
/////////////////////////

/////////////////////////////////
// Caption variables Declarations
extern char Image2_Caption[];
extern char Image4_Caption[];
extern char temperature_label_Caption[];
extern char Label1_Caption[];
extern char Label2_Caption[];
extern char humidity_label_Caption[];
extern char Label3_Caption[];
extern char uv_label_Caption[];
extern char Label4_Caption[];
extern char Label5_Caption[];
extern char Label6_Caption[];
extern char Label10_Caption[];
extern char Circle1_Caption[];
extern char ButtonRound1_Caption[];
extern char Image6_Caption[];
extern char Image7_Caption[];
extern char Image8_Caption[];
extern char Image9_Caption[];
extern char Image10_Caption[];
extern char Image3_Caption[];
extern char ProgressBar1_Caption[];
extern char servo_position_button_2_Caption[];
extern char servo_position_button_1_Caption[];
extern char Image5_Caption[];
extern char servo_number_button_1_Caption[];
extern char servo_number_button_2_Caption[];
extern char servo_number_button_4_Caption[];
extern char servo_number_button_6_Caption[];
extern char servo_number_button_5_Caption[];
extern char servo_number_button_7_Caption[];
extern char servo_number_button_8_Caption[];
extern char servo_number_button_9_Caption[];
extern char servo_number_button_10_Caption[];
extern char servo_number_button_11_Caption[];
extern char servo_number_button_12_Caption[];
extern char servo_number_button_13_Caption[];
extern char servo_number_button_14_Caption[];
extern char servo_number_button_15_Caption[];
extern char servo_number_button_16_Caption[];
extern char servo_number_button_3_Caption[];
extern char servo_number_button_all_Caption[];
extern char servo_position_button_3_Caption[];
extern char servo_position_button_4_Caption[];
extern char servo_position_button_5_Caption[];
extern char servo_position_button_6_Caption[];
extern char servo_position_button_7_Caption[];
extern char servo_position_button_8_Caption[];
extern char servo_position_button_9_Caption[];
extern char fan_speed_button_1_Caption[];
extern char fan_speed_button_3_Caption[];
extern char fan_speed_button_5_Caption[];
extern char fan_speed_button_stop_Caption[];
extern char Label7_Caption[];
extern char Label8_Caption[];
extern char Label9_Caption[];
extern char fan_speed_button_7_Caption[];
extern char ButtonRound2_Caption[];
extern char fan_speed_button_2_Caption[];
extern char fan_speed_button_4_Caption[];
extern char fan_speed_button_6_Caption[];
extern char Image1_Caption[];
/////////////////////////////////

void DrawScreen(TScreen *aScreen);
void DrawButton(TButton *aButton);
void DrawRoundButton(TButton_Round *Around_button);
void DrawLabel(TLabel *ALabel);
void DrawImage(TImage *AImage);
void DrawCircle(TCircle *ACircle);
void DrawProgressBar(TProgressBar *AProgressBar);
void UpdatePBPosition(TProgressBar *AProgressBar);
void Check_TP();
void Start_TP();
void Process_TP_Press(unsigned int X, unsigned int Y);
void Process_TP_Up(unsigned int X, unsigned int Y);
void Process_TP_Down(unsigned int X, unsigned int Y);
void updateLabel( uint8_t * tftLabel, uint16_t x, uint16_t y );
void cleanLabel( uint8_t label_no );